/*
 * generated by Xtext
 */
package rs.dsl.data.validation

import org.eclipse.xtext.validation.Check
import rs.dsl.data.dataDsl.DataDslPackage
import rs.dsl.data.dataDsl.Entity

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class DataValidator extends AbstractDataValidator {

	@Check
	def void checkNameStartsWithCapital(Entity entity) {
  		if (!Character::isUpperCase(entity.getName().charAt(0))) {
    		warning("Name should start with a capital", 
      		DataDslPackage.Literals::ABSTRACT_ELEMENT__NAME);
  		}
	}
	
}
