/*
 * generated by Xtext
 */
package rs.dsl.data.ui.contentassist

import rs.dsl.data.ui.contentassist.AbstractDataProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DataProposalProvider extends AbstractDataProposalProvider {
}
