/*
 * generated by Xtext
 */
package rs.dsl.data.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DataUiModule extends rs.dsl.data.ui.AbstractDataUiModule {
	public DataUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
